### ISSUE TITLE
%表示について

### ISSUE THREAD

**Issue by c0b21047** [C0B21063/ProjExD#4]
https://github.com/C0B21063/ProjExD/blob/ee7e4a083f75b08c8445708227888784c8e6ebaf/ex02/calc.py#L38
％表示をするならば、値の後ろに%を付けてみてはいかがでしょうか

**Comment by C0B21063** [comment]
×0.01という意味で追加したものだったので、別で追加することを検討しようと思います。
ありがとうございます。
